server:
  port: 8081

spring:
  application:
    name: ms-tarjetas
  datasource:
    url: jdbc:mysql://localhost:3307/appdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Lima
    username: app
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
